services:
  go-service:
    build: ./go-web/Golang_docker
    container_name: go-service
    ports:
      - "9990:9990"

  java-service:
    build: ./java-web/SpringJava_docker
    container_name: java-service
    ports:
      - "8080:8080"

  laravel-service:
    build: ./laravel-web/laravel-realworld-example-app
    container_name: laravel-service
    ports:
      - "8000:80"
